services:
  - type: web
    name: portfolio-website
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn portfolio.wsgi:application"
    plan: free
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: PYTHON_VERSION
        value: 3.12.0
