# Generated by Django 6.0.5 on 2026-05-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Your Name", max_length=100)),
                (
                    "title",
                    models.CharField(
                        default="Your Title",
                        help_text="Displayed below your name, e.g. 'Software Engineer'",
                        max_length=200,
                    ),
                ),
                (
                    "typed_items",
                    models.CharField(
                        default="Developer,Designer,Engineer",
                        help_text="Comma-separated list for the animated typing effect, e.g. Developer,Designer,Engineer",
                        max_length=500,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Write a short intro about yourself here."
                    ),
                ),
                ("profile_image", models.ImageField(blank=True, upload_to="home/")),
                (
                    "cta_primary_text",
                    models.CharField(default="View My Work", max_length=50),
                ),
                (
                    "cta_primary_url",
                    models.CharField(default="#portfolio", max_length=200),
                ),
                (
                    "cta_secondary_text",
                    models.CharField(default="Get In Touch", max_length=50),
                ),
                (
                    "cta_secondary_url",
                    models.CharField(default="#contact", max_length=200),
                ),
                (
                    "social_github",
                    models.URLField(blank=True, verbose_name="GitHub URL"),
                ),
                (
                    "social_linkedin",
                    models.URLField(blank=True, verbose_name="LinkedIn URL"),
                ),
                (
                    "social_twitter",
                    models.URLField(blank=True, verbose_name="Twitter / X URL"),
                ),
                (
                    "social_instagram",
                    models.URLField(blank=True, verbose_name="Instagram URL"),
                ),
                (
                    "social_facebook",
                    models.URLField(blank=True, verbose_name="Facebook URL"),
                ),
            ],
            options={
                "verbose_name": "Home Section",
                "verbose_name_plural": "Home Section",
            },
        ),
    ]
