# Generated by Django 6.0.5 on 2026-05-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_homesection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homesection",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="homesection",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Large heading, e.g. 'My Portfolio'",
                max_length=200,
            ),
        ),
    ]
