# Generated by Django 6.0.5 on 2026-05-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_homesection_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_image", models.ImageField(blank=True, upload_to="about/")),
                ("name", models.CharField(default="Your Name", max_length=100)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Subtitle shown below name, e.g. 'Creative Director & Developer'",
                        max_length=200,
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("location", models.CharField(blank=True, default="", max_length=200)),
                (
                    "badge_text",
                    models.CharField(
                        blank=True, default="Get to Know Me", max_length=100
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        blank=True,
                        default="Passionate About Creating Digital Experiences",
                        max_length=300,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "resume_url",
                    models.CharField(
                        blank=True,
                        default="#",
                        help_text="Link to downloadable CV/resume file",
                        max_length=200,
                    ),
                ),
                (
                    "stat1_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "stat1_label",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "stat2_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "stat2_label",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "stat3_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "stat3_label",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "detail1_label",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "detail1_value",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "detail2_label",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "detail2_value",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "detail3_label",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "detail3_value",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "detail4_label",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "detail4_value",
                    models.CharField(blank=True, default="", max_length=200),
                ),
            ],
            options={
                "verbose_name": "About Section",
                "verbose_name_plural": "About Section",
            },
        ),
    ]
