# Generated by Django 6.0.5 on 2026-05-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_homesection_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homesection",
            name="card_email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="Contact email"
            ),
        ),
        migrations.AddField(
            model_name="homesection",
            name="card_first_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="First name"
            ),
        ),
        migrations.AddField(
            model_name="homesection",
            name="card_last_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Last name"
            ),
        ),
        migrations.AddField(
            model_name="homesection",
            name="card_role",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. Software Engineer",
                max_length=100,
                verbose_name="Role / Title",
            ),
        ),
        migrations.AddField(
            model_name="homesection",
            name="tech_chips",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Comma-separated labels shown as tags, e.g. Python,Django,React",
                max_length=500,
                verbose_name="Tech stack chips",
            ),
        ),
    ]
