# Generated by Django 6.0.5 on 2026-05-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_add_badge_and_chips_to_homesection"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_image", models.ImageField(blank=True, upload_to="about/")),
                ("name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Title / Role",
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("location", models.CharField(blank=True, default="", max_length=100)),
                (
                    "badge_text",
                    models.CharField(
                        blank=True, default="Get to Know Me", max_length=60
                    ),
                ),
                ("heading", models.CharField(blank=True, default="", max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "stat1_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. 10+",
                        max_length=20,
                        verbose_name="Stat 1 number",
                    ),
                ),
                (
                    "stat1_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. Projects Completed",
                        max_length=50,
                        verbose_name="Stat 1 label",
                    ),
                ),
                (
                    "stat2_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Stat 2 number",
                    ),
                ),
                (
                    "stat2_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Stat 2 label",
                    ),
                ),
                (
                    "stat3_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Stat 3 number",
                    ),
                ),
                (
                    "stat3_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Stat 3 label",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Experience Level",
                    ),
                ),
                ("education", models.CharField(blank=True, default="", max_length=100)),
                ("languages", models.CharField(blank=True, default="", max_length=100)),
                (
                    "resume_url",
                    models.CharField(
                        blank=True,
                        default="#",
                        help_text="URL or path to downloadable resume file",
                        max_length=200,
                        verbose_name="Resume URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "About Section",
                "verbose_name_plural": "About Section",
            },
        ),
    ]
