# Generated by Django 6.0.5 on 2026-05-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_skill_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("issuer", models.CharField(max_length=200)),
                ("date", models.CharField(help_text="e.g. June 2024", max_length=100)),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="Link to the certificate (optional)"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Certificate",
                "verbose_name_plural": "Certificates",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        help_text="e.g. B.Sc. Computer Science", max_length=200
                    ),
                ),
                ("institution", models.CharField(max_length=200)),
                (
                    "period",
                    models.CharField(help_text="e.g. 2018 – 2022", max_length=100),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Education",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. Software Engineer", max_length=200
                    ),
                ),
                ("company", models.CharField(max_length=200)),
                (
                    "period",
                    models.CharField(help_text="e.g. 2022 – Present", max_length=100),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experience",
                "ordering": ["order"],
            },
        ),
    ]
