# Generated by Django 6.0.5 on 2026-05-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_certificate_education_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="image",
            field=models.ImageField(blank=True, upload_to="resume/certificates/"),
        ),
        migrations.AddField(
            model_name="education",
            name="image",
            field=models.ImageField(blank=True, upload_to="resume/education/"),
        ),
        migrations.AddField(
            model_name="experience",
            name="image",
            field=models.ImageField(blank=True, upload_to="resume/experience/"),
        ),
    ]
