# Generated by Django 6.0.5 on 2026-05-10 19:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_certificate_image_education_image_experience_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="date",
        ),
        migrations.RemoveField(
            model_name="education",
            name="period",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="period",
        ),
        migrations.AddField(
            model_name="certificate",
            name="issue_month",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ],
                default=1,
                verbose_name="Issue month",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="issue_year",
            field=models.PositiveIntegerField(
                default=core.models._current_year, verbose_name="Issue year"
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="end_month",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ],
                null=True,
                verbose_name="End month",
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="end_year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Leave blank for 'Present'",
                null=True,
                verbose_name="End year",
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="start_month",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ],
                default=9,
                verbose_name="Start month",
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="start_year",
            field=models.PositiveIntegerField(
                default=core.models._current_year, verbose_name="Start year"
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="end_month",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ],
                null=True,
                verbose_name="End month",
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="end_year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Leave blank for 'Present'",
                null=True,
                verbose_name="End year",
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="start_month",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ],
                default=1,
                verbose_name="Start month",
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="start_year",
            field=models.PositiveIntegerField(
                default=core.models._current_year, verbose_name="Start year"
            ),
        ),
    ]
