# Generated by Django 6.0.5 on 2026-05-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_remove_certificate_date_remove_education_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="pdf",
            field=models.FileField(
                blank=True,
                help_text="PDF file of the certificate (optional)",
                upload_to="resume/certificates/pdfs/",
            ),
        ),
    ]
