# Generated by Django 6.0.5 on 2026-05-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_certificate_add_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="credential_id",
            field=models.CharField(
                blank=True,
                help_text="Unique identifier issued by the organization (shown as 'Credential ID' on LinkedIn).",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="The logo of the issuer.",
                upload_to="resume/certificates/",
            ),
        ),
    ]
