# Generated by Django 6.0.5 on 2026-05-11 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_certificate_add_credential_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="pdf",
        ),
    ]
