# Generated by Django 6.0.5 on 2026-05-11 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_certificate_remove_pdf"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Project Category",
                "verbose_name_plural": "Project Categories",
                "ordering": ["order"],
            },
        ),
        migrations.RemoveField(
            model_name="project",
            name="url",
        ),
        migrations.AddField(
            model_name="project",
            name="featured",
            field=models.BooleanField(
                default=False, help_text="Pin to the top of the portfolio."
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="github_url",
            field=models.URLField(
                blank=True,
                help_text="Link to the source code repository.",
                verbose_name="GitHub URL",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="highlights",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Key features or highlights, one per line.",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="live_url",
            field=models.URLField(
                blank=True,
                help_text="Link to the deployed project.",
                verbose_name="Live URL",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="role",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Your role, e.g. Full Stack Developer.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="short_description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Brief summary shown on the portfolio card.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("in_progress", "In Progress"),
                    ("archived", "Archived"),
                ],
                default="completed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tech_stack",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Comma-separated technologies, e.g. Python,Django,React",
                max_length=500,
                verbose_name="Tech stack",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Full description for the project detail page.",
            ),
        ),
        migrations.RemoveField(
            model_name="project",
            name="category",
        ),
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="core.projectcategory",
            ),
        ),
    ]
