# Generated by Django 6.0.5 on 2026-05-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_portfolio_category_and_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, upload_to="portfolio/"),
        ),
    ]
