# Generated by Django 6.0.5 on 2026-05-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_project_image_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcategory",
            name="icon",
            field=models.CharField(
                choices=[
                    ("bi-code-slash", "Code / Programming"),
                    ("bi-laptop", "Laptop / Computer"),
                    ("bi-cpu", "CPU / Hardware"),
                    ("bi-bar-chart-line", "Bar Chart / Analytics"),
                    ("bi-graph-up", "Graph / Statistics"),
                    ("bi-database", "Database"),
                    ("bi-braces", "Braces / JSON"),
                    ("bi-terminal", "Terminal / CLI"),
                    ("bi-cloud-upload", "Cloud"),
                    ("bi-robot", "Robot / AI"),
                    ("bi-calculator", "Calculator / Maths"),
                    ("bi-diagram-3", "Diagram / Architecture"),
                    ("bi-layers", "Layers / Stack"),
                    ("bi-puzzle", "Puzzle / Problem Solving"),
                    ("bi-shield-check", "Security / Cybersecurity"),
                    ("bi-phone", "Mobile / App"),
                    ("bi-globe", "Web / Network"),
                    ("bi-eye", "Computer Vision"),
                    ("bi-chat-dots", "NLP / Chat"),
                    ("bi-grid-3x3", "Grid / Data Table"),
                ],
                default="bi-code-slash",
                help_text="Icon shown on the portfolio card.",
                max_length=50,
            ),
        ),
    ]
