# Generated by Django 6.0.5 on 2026-05-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_projectcategory_add_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="short_description",
        ),
        migrations.AddField(
            model_name="project",
            name="company",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Company or institution the project was done for.",
                max_length=300,
                verbose_name="Company / Institution",
            ),
        ),
    ]
