# Generated by Django 6.0.5 on 2026-05-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_rename_short_description_to_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="date",
            field=models.DateField(
                blank=True,
                help_text="Month and year this project was completed or delivered.",
                null=True,
                verbose_name="Project date",
            ),
        ),
    ]
