# Generated by Django 6.0.5 on 2026-05-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_add_project_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="date",
        ),
        migrations.AddField(
            model_name="project",
            name="end_month",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ],
                null=True,
                verbose_name="End month",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="end_year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Leave blank for 'Present'",
                null=True,
                verbose_name="End year",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="start_month",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ],
                null=True,
                verbose_name="Start month",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="start_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Start year"
            ),
        ),
    ]
