# Generated by Django 6.0.5 on 2026-05-11 18:21

from django.db import migrations, models
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    Project = apps.get_model("core", "Project")
    for project in Project.objects.all():
        base = slugify(project.title) or f"project-{project.pk}"
        slug, n = base, 1
        while Project.objects.filter(slug=slug).exclude(pk=project.pk).exists():
            slug = f"{base}-{n}"
            n += 1
        project.slug = slug
        project.save(update_fields=["slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_replace_project_date_with_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, default=""),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
