# Generated by Django 6.0.5 on 2026-05-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_add_project_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(blank=True, upload_to="recommendations/"),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Their job title, e.g. Senior Engineer",
                        max_length=200,
                    ),
                ),
                ("company", models.CharField(max_length=200)),
                ("quote", models.TextField(help_text="The recommendation text.")),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Recommendation",
                "verbose_name_plural": "Recommendation Section",
                "ordering": ["order"],
            },
        ),
    ]
