# Generated by Django 6.0.5 on 2026-05-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_recommendation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "info_heading",
                    models.CharField(default="Let's Connect", max_length=100),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional subtitle shown under the section heading.",
                        max_length=200,
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("location", models.CharField(blank=True, default="", max_length=100)),
                (
                    "linkedin_url",
                    models.URLField(blank=True, verbose_name="LinkedIn URL"),
                ),
                ("github_url", models.URLField(blank=True, verbose_name="GitHub URL")),
                (
                    "twitter_url",
                    models.URLField(blank=True, verbose_name="Twitter / X URL"),
                ),
                (
                    "form_heading",
                    models.CharField(default="Send a Message", max_length=100),
                ),
            ],
            options={
                "verbose_name": "Contact Section",
                "verbose_name_plural": "Contact Section",
            },
        ),
    ]
