# Generated by Django 6.0.5 on 2026-05-13 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_contactsection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="company",
        ),
        migrations.AddField(
            model_name="project",
            name="linked_education",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="core.education",
                verbose_name="Education (school)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="linked_experience",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="core.experience",
                verbose_name="Experience (company)",
            ),
        ),
    ]
