# Generated by Django 6.0.5 on 2026-06-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_remove_project_company_project_linked_education_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutsection",
            name="resume_url",
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="resume_file",
            field=models.FileField(
                blank=True,
                help_text="Upload a PDF. Replaces any previously uploaded file.",
                upload_to="resume/",
                verbose_name="Resume File",
            ),
        ),
    ]
