# Generated by Django 6.0.5 on 2026-06-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneralSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="Browser tab icon. A square .png (32×32 or 64×64) works best.",
                        upload_to="general/",
                    ),
                ),
            ],
            options={
                "verbose_name": "General Settings",
                "verbose_name_plural": "General Settings",
            },
        ),
    ]
