# Generated by Django 6.0.5 on 2026-06-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsettings",
            name="site_name",
            field=models.CharField(
                default="Portfolio",
                help_text="Name shown in the browser tab title and page headings.",
                max_length=100,
            ),
        ),
    ]
