# Generated by Django 6.0.5 on 2026-06-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0002_generalsettings_site_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsettings",
            name="og_image",
            field=models.ImageField(
                blank=True,
                help_text="Image shown when sharing on WhatsApp, Twitter, etc. Recommended: 1200×630 px. Falls back to the favicon if left blank.",
                upload_to="general/",
                verbose_name="Social preview image (OG image)",
            ),
        ),
    ]
