# Generated by Django 6.0.5 on 2026-06-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0003_generalsettings_og_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsettings",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="One or two sentences shown in Google search results. Keep under 160 characters.",
                max_length=160,
                verbose_name="Meta description",
            ),
        ),
    ]
